apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-edgex-core-metadata
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-edgex-core-metadata
  ports:
    - port: 48081
      name: port-48081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-edgex-core-metadata
  labels:
    app: {{ .Release.Name }}-edgex-core-metadata
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Release.Name }}-edgex-core-metadata
  template:
    metadata:
      name: edgex-core-metadata
      labels:
        app: {{ .Release.Name }}-edgex-core-metadata
    spec:
      containers:
        - name: edgex-core-metadata
          image: nexus3.edgexfoundry.org:10004/docker-core-metadata-go:1.1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 48081
          env:
            - name: "edgex_registry"
              value: consul://{{ .Release.Name }}-edgex-core-consul:8500
          readinessProbe:
            httpGet:
              path: /api/v1/ping
              port: 48081
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /api/v1/ping
              port: 48081
            initialDelaySeconds: 15
            periodSeconds: 20
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-edgex-core-metadata
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: metadata.{{ .Release.Name }}
      http:
        paths:
          - path: /(.*)
            backend:
              serviceName: {{ .Release.Name }}-edgex-core-metadata
              servicePort: 48081