kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
  - edgex-config-seed.yaml
  - edgex-core-command.yaml
  - edgex-core-consul.yaml
  - edgex-core-data.yaml
  - edgex-core-metadata.yaml
  - edgex-device-virtual.yaml
  - edgex-export-client.yaml
  - edgex-export-distro.yaml
  - edgex-mongo.yaml
  - edgex-support-logging.yaml
  - edgex-support-notifications.yaml
  - edgex-support-rulesengine.yaml
  - edgex-support-scheduler.yaml
