apiVersion: v1
kind: Pod
metadata:
  name: edgex-config-seed
  labels:
    app: edgex-config-seed
spec:
  containers:
    - name: edgex-config-seed
      image: edgexfoundry/docker-core-config-seed-go:1.0.0
  restartPolicy: OnFailure
  initContainers:
    - name: init-consul
      image: busybox:1.28
      command: ['sh', '-c', 'sleep 20']
